# ####################################################
# ##                                                ##
# #               AREONSYSTEM VON Danny              #
# #                                                  #
# #               SPIGOT VERSION: 1.12.2              #
# #                                                  #
# #         PLUGIN VERSION: 1.0 RELEASE       #
# ##                                                ##
# ####################################################

Prefix:
  Prefix: '&b&lAREON &7| '

useChatFormat: true
useColorTranslate: true
# patchholder -> %chatPrefix%, %playerName%, %message%, %ping%, %displayName%, %group%
chatFormat: '%chatPrefix%%playerName% &8\xbb &7%message%'
# update automatically the Tablist
autoUpdate: true
# format -> "group;tabPrefix;chatPrefix"
prefixes:
  - "owner;&4Owner &7| &4;&4Owner &7- &4"
  - "default;&7Player &7| ;&7Player - "
